package com.athomas5.javaspring;

public enum LifecycleStatus {
    LIFECYCLE_DRAFT,
    LIFECYCLE_UNDER_REVIEW,
    LIFECYCLE_SCHEDULED,
    LIFECYCLE_LIVE,
    LIFECYCLE_PAUSED,
    LIFECYCLE_COMPLETED,
    LIFECYCLE_SUNSETTED,
    LIFECYCLE_CANCELLED,
    LIFECYCLE_TEST,
    LIFECYCLE_APPROVED,
    LIFECYCLE_REJECTED,
}
